<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Santiago Álvarez Tostado Estrada">
<meta name="author" content="Francisco Uriel Ledezma Chávez">
<meta name="author" content="Jorge Isaac López Ávila">
<meta name="author" content="Juan Pablo Morán Errejón">

<title>El activo y su negocio – Análisis de Riesgo · GAPB</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-1e796f7a7bf16e5eb5298f63857716ad.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-56c9fb2a36a481e37cf6329f2f24e7ca.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Análisis de Riesgo · GAPB</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./01-asset-profile.html" aria-current="page"> 
<span class="menu-text">01 · Activo</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-price-history-events.html"> 
<span class="menu-text">02 · Precio y eventos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./03-returns-volatility-gbm.html"> 
<span class="menu-text">03 · Rendimientos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./04-variance-models.html"> 
<span class="menu-text">04 · Volatilidad</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./05-value-at-risk.html"> 
<span class="menu-text">05 · VaR</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Urielledezma/Analisis-de-Riesgo"> <i class="bi bi-github" role="img" aria-label="Repositorio en GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#descripción-general-del-activo-y-del-negocio" id="toc-descripción-general-del-activo-y-del-negocio" class="nav-link" data-scroll-target="#descripción-general-del-activo-y-del-negocio"><span class="header-section-number">2</span> Descripción general del activo y del negocio</a></li>
  <li><a href="#análisis-de-estados-financieros" id="toc-análisis-de-estados-financieros" class="nav-link" data-scroll-target="#análisis-de-estados-financieros"><span class="header-section-number">3</span> Análisis de estados financieros</a></li>
  <li><a href="#indicadores-financieros-clave" id="toc-indicadores-financieros-clave" class="nav-link" data-scroll-target="#indicadores-financieros-clave"><span class="header-section-number">4</span> Indicadores financieros clave</a></li>
  <li><a href="#utilidad-por-acción" id="toc-utilidad-por-acción" class="nav-link" data-scroll-target="#utilidad-por-acción"><span class="header-section-number">5</span> Utilidad por acción</a></li>
  <li><a href="#dividendos-y-splits" id="toc-dividendos-y-splits" class="nav-link" data-scroll-target="#dividendos-y-splits"><span class="header-section-number">6</span> Dividendos y <em>splits</em></a></li>
  <li><a href="#identificación-de-riesgos" id="toc-identificación-de-riesgos" class="nav-link" data-scroll-target="#identificación-de-riesgos"><span class="header-section-number">7</span> Identificación de riesgos</a></li>
  <li><a href="#conclusión" id="toc-conclusión" class="nav-link" data-scroll-target="#conclusión"><span class="header-section-number">8</span> Conclusión</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias"><span class="header-section-number">9</span> Referencias</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Urielledezma/Analisis-de-Riesgo/blob/main/01-asset-profile.qmd" class="toc-action"><i class="bi bi-github"></i>Ver el código</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">El activo y su negocio</h1>
<p class="subtitle lead">Grupo Aeroportuario del Pacífico · BMV: GAPB</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Santiago Álvarez Tostado Estrada </p>
             <p>Francisco Uriel Ledezma Chávez </p>
             <p>Jorge Isaac López Ávila </p>
             <p>Juan Pablo Morán Errejón </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2 de septiembre de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<dl class="report-meta" aria-label="Ficha técnica del reporte">
<div>
<dt>
Fuente de datos
</dt>
<dd>
GAP / SEC y serie pública de EPS; FactSet manual si está disponible
</dd>
</div>
<div>
<dt>
Corte financiero
</dt>
<dd>
31 de diciembre de 2025
</dd>
</div>
<div>
<dt>
Moneda
</dt>
<dd>
MXN millones; EPS en USD por ADS
</dd>
</div>
<div>
<dt>
Periodo cubierto
</dt>
<dd>
Estados 2023–2025; EPS 1T19–4T25
</dd>
</div>
</dl>
<section id="introducción" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">1</span> Introducción</h2>
<p>Esta primera etapa caracteriza a Grupo Aeroportuario del Pacífico, S.A.B. de C.V. (GAP) antes de modelar el riesgo de mercado de su acción serie B. El análisis combina la estructura económica del negocio con resultados consolidados de 2023 a 2025, indicadores de rentabilidad y apalancamiento, utilidad trimestral por ADS y política de dividendos. La lectura conjunta muestra una concesionaria con alta generación operativa y crecimiento, aunque expuesta a regulación tarifaria, tráfico aéreo, deuda y grandes compromisos de inversión.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Criterio de fuentes">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Criterio de fuentes
</div>
</div>
<div class="callout-body-container callout-body">
<p>ITESO confirmó que la licencia institucional de FactSet no incluye acceso por API. El repositorio acepta exportaciones manuales de FactSet en <code>data/raw/factset/manual/</code> y las conserva fuera de Git; en su ausencia, esta versión usa estados de resultados publicados por GAP ante la SEC y una serie pública de EPS. El informe nunca consulta una API durante el renderizado.</p>
</div>
</div>
</section>
<section id="descripción-general-del-activo-y-del-negocio" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="descripción-general-del-activo-y-del-negocio"><span class="header-section-number">2</span> Descripción general del activo y del negocio</h2>
<p>GAP administra infraestructura aeroportuaria bajo concesión: doce aeropuertos en México y los aeropuertos de Montego Bay y Kingston en Jamaica. Sus activos principales incluyen Guadalajara, Tijuana, Los Cabos y Puerto Vallarta, de modo que el portafolio combina tráfico de negocios, manufactura fronteriza y turismo internacional. La sociedad surgió del proceso de privatización aeroportuaria de 1998, inició la operación del paquete Pacífico en 1999 y cotiza desde 2006 en la BMV mediante GAPB y en Nueva York mediante el ADS PAC <span class="citation" data-cites="gap20f2025">(<a href="#ref-gap20f2025" role="doc-biblioref">Grupo Aeroportuario del Pacífico, 2026a</a>)</span>.</p>
<p>La <a href="#tbl-asset-metadata" class="quarto-xref">Tabla&nbsp;1</a> sintetiza la identificación bursátil utilizada en el análisis.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-asset-metadata" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-asset-metadata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;1: Identificación bursátil del emisor analizado.
</figcaption>
<div aria-describedby="tbl-asset-metadata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 38%">
<col style="width: 4%">
<col style="width: 9%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Ticker</th>
<th style="text-align: left;">Emisora</th>
<th style="text-align: left;">Serie</th>
<th style="text-align: left;">Sector</th>
<th style="text-align: left;">Industria</th>
<th style="text-align: left;">Identificador FactSet</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GAPB.MX</td>
<td style="text-align: left;">Grupo Aeroportuario del Pacífico, S.A.B. de C.V.</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">Industrials</td>
<td style="text-align: left;">Transportation Infrastructure</td>
<td style="text-align: left;">GAPB-MX</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>El ingreso económico se divide en servicios aeronáuticos —tarifas a pasajeros, aerolíneas y operadores— y no aeronáuticos —arrendamientos, alimentos y bebidas, estacionamientos, salas VIP, tiendas, publicidad, hotelería y carga—. En 2025 la mezcla, excluyendo la contabilidad de construcción de IFRIC 12, fue aproximadamente 70% aeronáutica y 30% no aeronáutica; esta diversificación reduce la dependencia de una sola tarifa, pero no elimina la dependencia del flujo de pasajeros. Los catorce aeropuertos atendieron 63.7 millones de pasajeros en 2025, 2.5% más que en 2024, y la plantilla cerró el ejercicio con aproximadamente 3,506 colaboradores <span class="citation" data-cites="gap4q2025 gap20f2025">(<a href="#ref-gap4q2025" role="doc-biblioref">Grupo Aeroportuario del Pacífico, 2026b</a>, <a href="#ref-gap20f2025" role="doc-biblioref">2026a</a>)</span>.</p>
<p>La posición competitiva proviene menos de una marca de consumo que de la exclusividad geográfica y la vida remanente de las concesiones. ASUR y OMA son los comparables mexicanos más cercanos, mientras que aeropuertos alternativos, carreteras y cambios en la oferta de las aerolíneas condicionan la demanda local. El evento corporativo más relevante posterior al cierre fue la combinación con Cross Border Xpress y activos de asistencia técnica, efectiva en mayo de 2026; amplía el ecosistema de Tijuana, pero también emitió acciones nuevas y abre un riesgo de integración que no pertenece todavía a las cifras 2025 analizadas aquí.</p>
</section>
<section id="análisis-de-estados-financieros" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="análisis-de-estados-financieros"><span class="header-section-number">3</span> Análisis de estados financieros</h2>
<p>IFRIC 12 obliga a reconocer como ingreso la construcción y mejora de activos concesionados junto con un costo equivalente. Como ese renglón infla ingreso y costo sin representar venta recurrente ni margen económico, se presentan dos bases: ingreso reportado y <strong>ingreso operativo</strong>, definido como la suma de servicios aeronáuticos y no aeronáuticos <span class="citation" data-cites="gap4q2024 gap4q2025">(<a href="#ref-gap4q2024" role="doc-biblioref">Grupo Aeroportuario del Pacífico, 2025b</a>, <a href="#ref-gap4q2025" role="doc-biblioref">2026b</a>)</span>.</p>
<p>La <a href="#tbl-financials" class="quarto-xref">Tabla&nbsp;2</a> presenta ambas bases y evita interpretar el ingreso de construcción como una venta recurrente.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-financials" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-financials-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;2: Resultados consolidados, millones de pesos corrientes.
</figcaption>
<div aria-describedby="tbl-financials-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Año</th>
<th style="text-align: right;">Ingreso reportado</th>
<th style="text-align: right;">Ingreso operativo</th>
<th style="text-align: right;">Utilidad operativa</th>
<th style="text-align: right;">Utilidad neta</th>
<th style="text-align: right;">EBITDA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2023</td>
<td style="text-align: right;">33,224</td>
<td style="text-align: right;">25,433</td>
<td style="text-align: right;">15,139</td>
<td style="text-align: right;">9,690</td>
<td style="text-align: right;">17,684</td>
</tr>
<tr class="even">
<td style="text-align: right;">2024</td>
<td style="text-align: right;">33,614</td>
<td style="text-align: right;">26,782</td>
<td style="text-align: right;">15,051</td>
<td style="text-align: right;">8,875</td>
<td style="text-align: right;">18,112</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2025</td>
<td style="text-align: right;">41,409</td>
<td style="text-align: right;">32,526</td>
<td style="text-align: right;">17,580</td>
<td style="text-align: right;">10,001</td>
<td style="text-align: right;">21,332</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>El ingreso operativo aumentó de $25,432.8 millones en 2023 a $32,525.9 millones en 2025, una expansión acumulada de 27.9%. El avance de 2025 fue especialmente fuerte: 21.4% frente a 2024, apoyado por recuperación de tráfico, ajuste de tarifas, depreciación del peso sobre los ingresos jamaiquinos y consolidación de carga y zona franca. La utilidad neta creció 12.7% en ese último año, menos que el ingreso, señal de que la escala adicional llegó acompañada de mayor costo financiero, depreciación y gasto operativo <span class="citation" data-cites="gap4q2025">(<a href="#ref-gap4q2025" role="doc-biblioref">Grupo Aeroportuario del Pacífico, 2026b</a>)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-margins" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-margins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-asset-profile_files/figure-html/fig-margins-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1600">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-margins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Márgenes consolidados bajo base reportada y base operativa sin IFRIC 12.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-margins" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-margins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;3: Márgenes comparables por ejercicio.
</figcaption>
<div aria-describedby="tbl-margins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 21%">
<col style="width: 18%">
<col style="width: 21%">
<col style="width: 16%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Año</th>
<th style="text-align: right;">Servicios sin IFRIC 12</th>
<th style="text-align: right;">Operativo reportado</th>
<th style="text-align: right;">Operativo sin IFRIC 12</th>
<th style="text-align: right;">Neto sin IFRIC 12</th>
<th style="text-align: right;">EBITDA sin IFRIC 12</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2023</td>
<td style="text-align: right;">82.8%</td>
<td style="text-align: right;">45.6%</td>
<td style="text-align: right;">59.5%</td>
<td style="text-align: right;">38.1%</td>
<td style="text-align: right;">69.5%</td>
</tr>
<tr class="even">
<td style="text-align: right;">2024</td>
<td style="text-align: right;">80.3%</td>
<td style="text-align: right;">44.8%</td>
<td style="text-align: right;">56.2%</td>
<td style="text-align: right;">33.1%</td>
<td style="text-align: right;">67.6%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2025</td>
<td style="text-align: right;">80.0%</td>
<td style="text-align: right;">42.5%</td>
<td style="text-align: right;">54.0%</td>
<td style="text-align: right;">30.7%</td>
<td style="text-align: right;">65.6%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>La <a href="#fig-margins" class="quarto-xref">Figura&nbsp;1</a> muestra la trayectoria y la <a href="#tbl-margins" class="quarto-xref">Tabla&nbsp;3</a> conserva los valores exactos que sostienen la comparación entre ejercicios.</p>
<div class="semantic-block semantic-assumption">
<p><span class="semantic-label">Supuesto metodológico</span></p>
<p>GAP no presenta un subtotal IFRS de utilidad bruta. Por ello, “servicios sin IFRIC 12” es un proxy explícito: ingreso operativo menos costo de servicios, dividido entre ingreso operativo; no incluye todavía impuestos a la concesión, asistencia técnica, depreciación ni otros costos operativos.</p>
</div>
<p>El margen EBITDA sin IFRIC 12 permaneció elevado, pero descendió de 69.5% en 2023 a 65.6% en 2025. El margen operativo comparable siguió el mismo patrón, de 59.5% a 54.0%; por tanto, el crecimiento no debe confundirse con expansión de eficiencia. La empresa conserva poder de generación de caja propio de una infraestructura concesionada, aunque su programa de inversión y la nueva escala presionan costos antes de que toda la capacidad produzca ingresos.</p>
</section>
<section id="indicadores-financieros-clave" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="indicadores-financieros-clave"><span class="header-section-number">4</span> Indicadores financieros clave</h2>
<p>La <a href="#tbl-ratios" class="quarto-xref">Tabla&nbsp;4</a> concentra rentabilidad, apalancamiento y capacidad de cobertura al cierre del ejercicio.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ratios" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ratios-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4: Indicadores clave al cierre de 2025.
</figcaption>
<div aria-describedby="tbl-ratios-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 28%">
<col style="width: 6%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Indicador</th>
<th style="text-align: right;">Valor</th>
<th style="text-align: left;">Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ROE</td>
<td style="text-align: right;">40.4%</td>
<td style="text-align: left;">Rentabilidad elevada sobre el capital contable promedio.</td>
</tr>
<tr class="even">
<td style="text-align: left;">ROA</td>
<td style="text-align: right;">11.8%</td>
<td style="text-align: left;">Los activos producen una utilidad de doble dígito.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deuda / capital</td>
<td style="text-align: right;">2.13x</td>
<td style="text-align: left;">La deuda equivale a más de dos veces el capital.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Deuda / EBITDA</td>
<td style="text-align: right;">2.48x</td>
<td style="text-align: left;">Cobertura operativa holgada, pero sensible a tasas y tráfico.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deuda neta / EBITDA</td>
<td style="text-align: right;">1.99x</td>
<td style="text-align: left;">La caja reduce el apalancamiento económico por debajo de 2x.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Margen EBITDA sin IFRIC 12</td>
<td style="text-align: right;">65.6%</td>
<td style="text-align: left;">Amplio colchón antes de intereses, impuestos y depreciación.</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>El ROE de 40.4% es atractivo, pero está amplificado por una estructura en la que la deuda representa 2.13 veces el capital. En contraste, la deuda neta equivale a 1.99 veces EBITDA, nivel administrable para la generación operativa actual. La lectura correcta no es “bajo riesgo”: GAP puede servir su deuda en el escenario base, pero una interrupción de tráfico o un aumento persistente de tasas se transmitiría con rapidez al flujo disponible para inversión y dividendos.</p>
</section>
<section id="utilidad-por-acción" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="utilidad-por-acción"><span class="header-section-number">5</span> Utilidad por acción</h2>
<p>La serie trimestral corresponde al ADS <strong>PAC</strong> cotizado en Nueva York, denominado en dólares y equivalente a diez acciones serie B; se usa porque ofrece una historia trimestral homogénea para el mismo derecho económico. No se mezcla con el precio de GAPB ni se convierte a pesos, ya que hacerlo introduciría el tipo de cambio dentro de una medida de desempeño operativo <span class="citation" data-cites="alphaquerypac marketbeatpac">(<a href="#ref-alphaquerypac" role="doc-biblioref">AlphaQuery, 2026</a>; <a href="#ref-marketbeatpac" role="doc-biblioref">MarketBeat, 2026</a>)</span>.</p>
<p>La <a href="#fig-eps" class="quarto-xref">Figura&nbsp;2</a> permite observar la ruptura y recuperación de la serie, mientras que la <a href="#tbl-eps" class="quarto-xref">Tabla&nbsp;5</a> conserva el detalle trimestral utilizado en la lectura.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-eps" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-asset-profile_files/figure-html/fig-eps-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1600">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-eps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Utilidad diluida trimestral por ADS PAC, dólares por ADS.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-eps" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-eps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;5: EPS diluido trimestral del ADS PAC, USD.
</figcaption>
<div aria-describedby="tbl-eps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Año</th>
<th style="text-align: right;">T1</th>
<th style="text-align: right;">T2</th>
<th style="text-align: right;">T3</th>
<th style="text-align: right;">T4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2019</td>
<td style="text-align: right;">1.30</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">1.33</td>
</tr>
<tr class="even">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">1.63</td>
<td style="text-align: right;">-0.45</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.30</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">1.26</td>
<td style="text-align: right;">1.73</td>
<td style="text-align: right;">1.70</td>
</tr>
<tr class="even">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">2.29</td>
<td style="text-align: right;">2.32</td>
<td style="text-align: right;">2.60</td>
<td style="text-align: right;">1.67</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2023</td>
<td style="text-align: right;">2.72</td>
<td style="text-align: right;">2.87</td>
<td style="text-align: right;">2.90</td>
<td style="text-align: right;">2.55</td>
</tr>
<tr class="even">
<td style="text-align: right;">2024</td>
<td style="text-align: right;">2.88</td>
<td style="text-align: right;">2.55</td>
<td style="text-align: right;">2.74</td>
<td style="text-align: right;">2.14</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2025</td>
<td style="text-align: right;">2.72</td>
<td style="text-align: right;">2.70</td>
<td style="text-align: right;">2.86</td>
<td style="text-align: right;">1.64</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>La ruptura de la serie ocurre en el segundo trimestre de 2020, cuando el EPS fue negativo por las restricciones de movilidad. La recuperación posterior es visible y, desde 2022, todos los trimestres permanecen positivos; sin embargo, el descenso a USD 1.64 en 4T25 frente a USD 2.86 en 3T25 confirma estacionalidad y sensibilidad del resultado financiero. Para las etapas de mercado interesa menos el nivel aislado que la capacidad de estos cambios para alterar expectativas y volatilidad.</p>
</section>
<section id="dividendos-y-splits" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="dividendos-y-splits"><span class="header-section-number">6</span> Dividendos y <em>splits</em></h2>
<p>La política de GAP distribuye efectivo excedente después de conservar un saldo mínimo equivalente a dos meses de gastos operativos y servicio de deuda de corto plazo. La asamblea de abril de 2025 aprobó un dividendo total de MXN 16.84 por acción, pagado en dos exhibiciones; la frecuencia, por tanto, depende de la asamblea y de la liquidez, no de un dividendo trimestral rígido <span class="citation" data-cites="gapdividend2025">(<a href="#ref-gapdividend2025" role="doc-biblioref">Grupo Aeroportuario del Pacífico, 2025a</a>)</span>. Esa flexibilidad protege inversión y deuda, aunque vuelve el retorno total sensible a decisiones corporativas y al ciclo de CAPEX.</p>
<p>No se identificaron <em>splits</em> de GAPB desde su listado en 2006 en los informes revisados. Sí existe una relación fija de un ADS PAC por diez acciones serie B, que no debe confundirse con un <em>split</em>. Las siguientes etapas utilizarán precio ajustado por distribuciones y eventos corporativos; esta distinción evita que un dividendo aparezca falsamente como pérdida económica.</p>
</section>
<section id="identificación-de-riesgos" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="identificación-de-riesgos"><span class="header-section-number">7</span> Identificación de riesgos</h2>
<div class="semantic-block semantic-risk">
<p><span class="semantic-label">Riesgo</span></p>
<p><strong>Riesgo regulatorio y de concesión.</strong> La tarifa máxima, los derechos de concesión y los programas maestros de desarrollo dependen de autoridades mexicanas y jamaiquinas. Una modificación unilateral cambia ingresos permitidos o CAPEX obligatorio y, por ello, afecta directamente la valuación.</p>
<p><strong>Riesgo de tráfico y concentración.</strong> Los ingresos dependen de pasajeros, rutas y capacidad de aerolíneas; choques sanitarios, recesión, problemas de motores o quiebras de operadores reducen simultáneamente ingreso aeronáutico y consumo comercial. La concentración en Guadalajara, Tijuana y destinos turísticos aumenta la exposición a eventos regionales y estacionales.</p>
<p><strong>Riesgo macrofinanciero.</strong> Tasas altas encarecen una deuda de MXN 53.0 mil millones, mientras que la depreciación del peso eleva la traducción de Jamaica pero también puede encarecer obligaciones o insumos en dólares. Inflación, crecimiento del PIB y tipo de cambio deben reaparecer como variables de contexto en la etapa 02.</p>
<p><strong>Riesgo de ejecución e integración.</strong> El CAPEX 2025 de MXN 12.4 mil millones y la integración posterior de CBX requieren disciplina operativa. Retrasos, sobrecostos o capacidad que tarde en madurar comprimirían márgenes y flujo libre; la emisión de acciones asociada, además, introduce dilución para el accionista.</p>
<p><strong>Riesgo climático, de seguridad y tecnológico.</strong> Huracanes, sismos, fallas de infraestructura, ciberataques o incidentes de seguridad pueden interrumpir un activo que no puede trasladarse. Aunque seguros y redundancias contienen la pérdida, no eliminan cierres, daño reputacional ni menor tráfico.</p>
</div>
</section>
<section id="conclusión" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="conclusión"><span class="header-section-number">8</span> Conclusión</h2>
<p>GAP llega al cierre de 2025 como una concesionaria en expansión: el ingreso operativo creció 27.9% en dos años, el EBITDA alcanzó MXN 21.3 mil millones y la deuda neta se mantuvo cerca de 2.0 veces EBITDA. La contrapartida es una compresión gradual de márgenes, deuda superior a dos veces el capital y un ciclo intenso de inversión, a lo que se suma la integración de CBX en 2026. En consecuencia, GAPB combina calidad de infraestructura y flujo recurrente con riesgos discretos capaces de producir saltos en precio; regulación, tráfico, tasas, tipo de cambio e integración serán los ejes que deberán contrastarse con la historia bursátil en la siguiente etapa.</p>
</section>
<section id="referencias" class="level2" data-number="9">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">9 Referencias</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-alphaquerypac" class="csl-entry" role="listitem">
AlphaQuery. (2026). <em>Grupo Aeroportuario del Pacífico: Earnings History</em>. <a href="https://www.alphaquery.com/stock/PAC/earnings-history">https://www.alphaquery.com/stock/PAC/earnings-history</a>
</div>
<div id="ref-gapdividend2025" class="csl-entry" role="listitem">
Grupo Aeroportuario del Pacífico. (2025a). <em>Pago de la segunda y última exhibición del dividendo aprobado en 2025</em>. <a href="https://www.aeropuertosgap.com.mx/es/comunicados-generales/4934-anuncio-fecha-dividendo-2025-julio.html">https://www.aeropuertosgap.com.mx/es/comunicados-generales/4934-anuncio-fecha-dividendo-2025-julio.html</a>
</div>
<div id="ref-gap4q2024" class="csl-entry" role="listitem">
Grupo Aeroportuario del Pacífico. (2025b). <em>Resultados consolidados del cuarto trimestre de 2024</em>. Grupo Aeroportuario del Pacífico. <a href="https://www.sec.gov/Archives/edgar/data/1347557/000117184325001044/f6k_022525.htm">https://www.sec.gov/Archives/edgar/data/1347557/000117184325001044/f6k_022525.htm</a>
</div>
<div id="ref-gap20f2025" class="csl-entry" role="listitem">
Grupo Aeroportuario del Pacífico. (2026a). <em>Annual Report 2025, Form 20-F</em>. U.S. Securities; Exchange Commission. <a href="https://www.sec.gov/Archives/edgar/data/1347557/000119312526161714/pac-20251231.htm">https://www.sec.gov/Archives/edgar/data/1347557/000119312526161714/pac-20251231.htm</a>
</div>
<div id="ref-gap4q2025" class="csl-entry" role="listitem">
Grupo Aeroportuario del Pacífico. (2026b). <em>Resultados consolidados del cuarto trimestre de 2025</em>. Grupo Aeroportuario del Pacífico. <a href="https://www.sec.gov/Archives/edgar/data/1347557/000117184326001035/f6k_022426.htm">https://www.sec.gov/Archives/edgar/data/1347557/000117184326001035/f6k_022426.htm</a>
</div>
<div id="ref-marketbeatpac" class="csl-entry" role="listitem">
MarketBeat. (2026). <em>Grupo Aeroportuario del Pacífico Earnings History</em>. <a href="https://www.marketbeat.com/stocks/NYSE/PAC/earnings/">https://www.marketbeat.com/stocks/NYSE/PAC/earnings/</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Licencia MIT · el contenido de terceros conserva los términos de su proveedor.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Urielledezma/Analisis-de-Riesgo/blob/main/01-asset-profile.qmd" class="toc-action"><i class="bi bi-github"></i>Ver el código</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Fuentes de mercado: Yahoo Finance / BMV · Macro: Banco Mundial</p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>